redis = "12800"
mode = "colocated"

[policy]
model_name_or_path = "stabilityai/stable-diffusion-3.5-medium"
is_diffusers = true
model_gradient_checkpointing = true

[policy.lora]
lora_names = ["default", "old"]
r = 32
lora_alpha = 64
init_lora_weights = "gaussian"
target_modules = [
    "attn.add_k_proj",
    "attn.add_q_proj",
    "attn.add_v_proj",
    "attn.to_add_out",
    "attn.to_k",
    "attn.to_out.0",
    "attn.to_q",
    "attn.to_v",
]

[policy.diffusers]
is_video = false
offload = false
max_prompt_length = 128
inference_size = [512, 512]
timestep_fraction = 0.99
nft_beta = 1.0
weight_copy_decay_type = 1

[policy.diffusers.sample]
num_steps = 10
eval_num_steps = 40
guidance_scale = 1.0
noise_level = 0.7
solver = "dpm2"
deterministic_sampling = true

[rollout]
backend = "diffusion_nft_rollout"
n_generation = 24

[logging]
logger = ['console', 'wandb']
project_name = "cosmos_rl"
experiment_name = "None"
multi_modal_log_interval = 10

[train]
non_text = true
resume = false
epoch = 100000
seed = 42
train_batch_per_replica = 1152  # 6*24*8
output_dir = "./outputs/stable-diffusion-3-5-medium-nft"
epsilon = 1e-8
optm_name = "AdamW"
optm_lr = 3e-4
optm_impl = "foreach"
optm_weight_decay = 1e-4
optm_betas = [ 0.9, 0.999,]
optm_grad_norm_clip = 1.0
optm_warmup_steps = 0
ema_enable = true
ema_decay = 0.9
ema_update_step_interval = 1
async_tp_enabled = false
compile = false
param_dtype = "bfloat16"
fsdp_reduce_dtype = "float32"
fsdp_offload = false
fsdp_reshard_after_forward = "default"

[train.train_policy]
type = "grpo"
trainer_type = "diffusion_nft"
uncentralized_training = true
use_remote_reward = true
dataset.name = "pickscore"
dataset.split = "train"
kl_beta = 0.0001
mini_batch = 9
advantage_high = 5.0
advantage_low = -5.0

[train.train_policy.remote_reward]
scale = 1.0

[[train.train_policy.remote_reward.reward_fns]]
name = "pickscore"
weight = 1.0

[train.ckpt]
enable_checkpoint = true
save_freq = 20
save_mode = "async"

[validation]
enable = false
val_before_train = true
freq = 10
batch_size = 128  # 16*8
dataset.name = "pickscore"
dataset.split = "test"

[rollout.parallelism]
n_init_replicas = 1
tp_size = 1
dp_shard_size = 8

[policy.parallelism]
n_init_replicas = 1
tp_size = 1
dp_shard_size = 8
